version: "3.9"
services:
  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "pg_balance_pass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - /docker_pg/Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    ports:
      - "8000:8000"
    links:
      - db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_HOST: db

